#!/usr/bin/env python3
"""AUC orientation diagnostics on held-out DCE predictions."""
from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from heldout_dce_validation import roc_auc

WORKSPACE = Path(__file__).resolve().parent
PREDICTIONS = WORKSPACE / "results" / "heldout_dce_predictions.csv"
OUT_CSV = WORKSPACE / "results" / "heldout_auc_orientations.csv"
OUT_TEX = WORKSPACE / "results" / "heldout_auc_orientations.tex"

METHODS = [
    ("Pure-DCE", "p_dce", lambda r: True),
    ("Unconstrained LLM", "p_llm", lambda r: r.get("p_llm") is not None),
    ("Static-BDT", "p_bdt", lambda r: r.get("p_bdt") is not None),
]


def load_rows() -> list[dict]:
    rows = list(csv.DictReader(open(PREDICTIONS, newline="", encoding="utf-8")))
    for r in rows:
        r["y"] = int(float(r["y"]))
        r["p_dce"] = float(r["p_dce"])
        r["matched"] = bool(str(r.get("matched_llm_state", "")).strip())
        if r.get("p_llm", "").strip():
            r["p_llm"] = float(r["p_llm"])
            r["p_bdt"] = float(r["p_bdt"])
        else:
            r["p_llm"] = None
            r["p_bdt"] = None
    return rows


def fmt_auc(v: float) -> str:
    return f"{v:.4f}" if not np.isnan(v) else "NA"


def auc_block(y: np.ndarray, p: np.ndarray) -> dict[str, float]:
    p = np.asarray(p, dtype=float)
    y = np.asarray(y, dtype=float)
    return {
        "auc_y_p": roc_auc(y, p),
        "auc_y_1mp": roc_auc(y, 1.0 - p),
        "auc_1my_p": roc_auc(1.0 - y, p),
    }


def evaluate(sample: str, subset: list[dict], method: str, col: str) -> dict:
    y = np.array([r["y"] for r in subset], dtype=float)
    p = np.array([r[col] for r in subset], dtype=float)
    aucs = auc_block(y, p)
    return {
        "sample": sample,
        "method": method,
        "N": len(subset),
        "auc_y_p": fmt_auc(aucs["auc_y_p"]),
        "auc_y_1mp": fmt_auc(aucs["auc_y_1mp"]),
        "auc_1my_p": fmt_auc(aucs["auc_1my_p"]),
        **{f"_{k}": v for k, v in aucs.items()},
    }


def write_tex(rows: list[dict]) -> None:
    lines = [
        "% Auto-generated by heldout_auc_orientations.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Held-out AUC by label/score orientation.}",
        "\\label{tab:heldout-auc-orientations}",
        "\\small",
    ]
    for sample in ("full", "matched"):
        sub = [r for r in rows if r["sample"] == sample]
        title = "Full held-out" if sample == "full" else "LLM-matched subsample"
        lines.append(f"\\textbf{{{title}}} ($N$ as listed)\\\\")
        lines.append("\\begin{tabular}{l r r r r}")
        lines.append("\\toprule")
        lines.append("Method & $N$ & AUC$(y,p)$ & AUC$(y,1-p)$ & AUC$(1-y,p)$ \\\\")
        lines.append("\\midrule")
        for r in sub:
            lines.append(
                f"{r['method']} & {r['N']} & {r['auc_y_p']} & {r['auc_y_1mp']} & {r['auc_1my_p']} \\\\"
            )
        lines.append("\\bottomrule")
        lines.append("\\end{tabular}")
        if sample == "full":
            lines.append("\\vspace{0.6em}")
    lines.append("\\end{table}")
    OUT_TEX.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    rows = load_rows()
    matched = [r for r in rows if r["matched"]]
    out: list[dict] = []

    for method, col, pred_ok in METHODS:
        full_sub = [r for r in rows if pred_ok(r)]
        out.append(evaluate("full", full_sub, method, col))
        out.append(evaluate("matched", [r for r in matched if pred_ok(r)], method, col))

    fields = ["sample", "method", "N", "auc_y_p", "auc_y_1mp", "auc_1my_p"]
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(out)

    write_tex(out)

    print("Held-out AUC orientations\n")
    for sample in ("full", "matched"):
        print(f"=== {sample.upper()} ===")
        print(f"{'Method':<22} {'N':>5}  AUC(y,p)  AUC(y,1-p)  AUC(1-y,p)")
        for r in out:
            if r["sample"] != sample:
                continue
            print(
                f"{r['method']:<22} {r['N']:>5}  {r['auc_y_p']:>8}  {r['auc_y_1mp']:>10}  {r['auc_1my_p']:>10}"
            )
        print()

    print(OUT_TEX.read_text(encoding="utf-8"))
    print(f"Wrote {OUT_CSV}")
    print(f"Wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
